// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SensESP Round Display

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_ARCunten;
extern lv_obj_t *ui_ARCoben;
extern void ui_event_SWon( lv_event_t * e);
extern lv_obj_t *ui_SWon;
extern lv_obj_t *ui_SWregen;
extern lv_obj_t *ui_LBLRegen;
extern lv_obj_t *ui_LBLonsw;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_LBLrpmlevel;
extern lv_obj_t *ui_LBLrpm;
extern lv_obj_t *ui_LBLzero;
extern lv_obj_t *ui_LBLForward;
extern lv_obj_t *ui_LBLrewards;
extern lv_obj_t *ui_Image4;
// CUSTOM VARIABLES
extern lv_obj_t *uic_LBLonsw;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

