// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SensESP Round Display

#include "ui.h"

lv_obj_t *uic_LBLonsw;
lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_ARCunten = NULL;lv_obj_t *ui_ARCoben = NULL;lv_obj_t *ui_SWon = NULL;lv_obj_t *ui_SWregen = NULL;lv_obj_t *ui_LBLRegen = NULL;lv_obj_t *ui_LBLonsw = NULL;lv_obj_t *ui_Panel1 = NULL;lv_obj_t *ui_LBLrpmlevel = NULL;lv_obj_t *ui_LBLrpm = NULL;lv_obj_t *ui_LBLzero = NULL;lv_obj_t *ui_LBLForward = NULL;lv_obj_t *ui_LBLrewards = NULL;lv_obj_t *ui_Image4 = NULL;
// event funtions
void ui_event_SWon( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_checked_set_text_value( ui_LBLonsw, target, "ON	", "OFF");
}
}

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ARCunten = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_ARCunten, 235);
lv_obj_set_height( ui_ARCunten, 235);
lv_obj_set_align( ui_ARCunten, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ARCunten, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_arc_set_range(ui_ARCunten, 0,4095);
lv_arc_set_value(ui_ARCunten, 1000);
lv_arc_set_bg_angles(ui_ARCunten,5,175);

lv_obj_set_style_bg_color(ui_ARCunten, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ARCunten, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_ARCoben = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_ARCoben, 230);
lv_obj_set_height( ui_ARCoben, 230);
lv_obj_set_align( ui_ARCoben, LV_ALIGN_CENTER );
lv_arc_set_range(ui_ARCoben, 0,4095);
lv_arc_set_value(ui_ARCoben, 2047);
lv_arc_set_bg_angles(ui_ARCoben,185,355);
lv_arc_set_mode(ui_ARCoben, LV_ARC_MODE_SYMMETRICAL);

ui_SWon = lv_switch_create(ui_Screen1);
lv_obj_set_width( ui_SWon, 100);
lv_obj_set_height( ui_SWon, 25);
lv_obj_set_x( ui_SWon, 0 );
lv_obj_set_y( ui_SWon, 48 );
lv_obj_set_align( ui_SWon, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_SWon, lv_color_hex(0x14FE00), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_SWon, 255, LV_PART_MAIN| LV_STATE_CHECKED);

lv_obj_set_style_bg_color(ui_SWon, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SWon, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SWon, lv_color_hex(0x14FE00), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_SWon, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);

ui_SWregen = lv_switch_create(ui_Screen1);
lv_obj_set_width( ui_SWregen, 100);
lv_obj_set_height( ui_SWregen, 25);
lv_obj_set_x( ui_SWregen, 0 );
lv_obj_set_y( ui_SWregen, 12 );
lv_obj_set_align( ui_SWregen, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_SWregen, lv_color_hex(0x0F2BFB), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_SWregen, 255, LV_PART_MAIN| LV_STATE_CHECKED);

lv_obj_set_style_bg_color(ui_SWregen, lv_color_hex(0xB7C2ED), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SWregen, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_SWregen, lv_color_hex(0x2B00FF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SWregen, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_LBLRegen = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_LBLRegen, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LBLRegen, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LBLRegen, 5 );
lv_obj_set_y( ui_LBLRegen, 12 );
lv_obj_set_align( ui_LBLRegen, LV_ALIGN_CENTER );
lv_label_set_text(ui_LBLRegen,"Gen");
lv_obj_clear_flag( ui_LBLRegen, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags

ui_LBLonsw = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_LBLonsw, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LBLonsw, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LBLonsw, 3 );
lv_obj_set_y( ui_LBLonsw, 48 );
lv_obj_set_align( ui_LBLonsw, LV_ALIGN_CENTER );
lv_label_set_text(ui_LBLonsw,"OFF");

ui_Panel1 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel1, 119);
lv_obj_set_height( ui_Panel1, 50);
lv_obj_set_x( ui_Panel1, 1 );
lv_obj_set_y( ui_Panel1, -50 );
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LBLrpmlevel = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_LBLrpmlevel, LV_SIZE_CONTENT);  /// 2
lv_obj_set_height( ui_LBLrpmlevel, LV_SIZE_CONTENT);   /// 2
lv_obj_set_x( ui_LBLrpmlevel, 1 );
lv_obj_set_y( ui_LBLrpmlevel, -48 );
lv_obj_set_align( ui_LBLrpmlevel, LV_ALIGN_CENTER );
lv_label_set_text(ui_LBLrpmlevel,"4500");
lv_label_set_recolor(ui_LBLrpmlevel,"true");
lv_obj_set_style_text_letter_space(ui_LBLrpmlevel, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_LBLrpmlevel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LBLrpmlevel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LBLrpmlevel, &lv_font_montserrat_42, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LBLrpm = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_LBLrpm, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LBLrpm, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LBLrpm, 92 );
lv_obj_set_y( ui_LBLrpm, -57 );
lv_obj_set_align( ui_LBLrpm, LV_ALIGN_CENTER );
lv_label_set_text(ui_LBLrpm,"RPM");
lv_obj_set_style_text_align(ui_LBLrpm, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_angle(ui_LBLrpm, 900, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LBLzero = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_LBLzero, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LBLzero, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LBLzero, 94 );
lv_obj_set_y( ui_LBLzero, 11 );
lv_obj_set_align( ui_LBLzero, LV_ALIGN_CENTER );
lv_label_set_text(ui_LBLzero,"0%");
lv_obj_set_style_text_font(ui_LBLzero, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LBLForward = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_LBLForward, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LBLForward, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LBLForward, -109 );
lv_obj_set_y( ui_LBLForward, -13 );
lv_obj_set_align( ui_LBLForward, LV_ALIGN_CENTER );
lv_label_set_text(ui_LBLForward,"F");

ui_LBLrewards = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_LBLrewards, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LBLrewards, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LBLrewards, 109 );
lv_obj_set_y( ui_LBLrewards, -12 );
lv_obj_set_align( ui_LBLrewards, LV_ALIGN_CENTER );
lv_label_set_text(ui_LBLrewards,"R");

ui_Image4 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image4, &ui_img_1183780206);
lv_obj_set_width( ui_Image4, LV_SIZE_CONTENT);  /// 96
lv_obj_set_height( ui_Image4, LV_SIZE_CONTENT);   /// 96
lv_obj_set_x( ui_Image4, 1 );
lv_obj_set_y( ui_Image4, 90 );
lv_obj_set_align( ui_Image4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_Image4,900);
lv_img_set_zoom(ui_Image4,100);

lv_obj_add_event_cb(ui_SWon, ui_event_SWon, LV_EVENT_ALL, NULL);
uic_LBLonsw = ui_LBLonsw;

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_ARCunten= NULL;
ui_ARCoben= NULL;
ui_SWon= NULL;
ui_SWregen= NULL;
ui_LBLRegen= NULL;
uic_LBLonsw= NULL;
ui_LBLonsw= NULL;
ui_Panel1= NULL;
ui_LBLrpmlevel= NULL;
ui_LBLrpm= NULL;
ui_LBLzero= NULL;
ui_LBLForward= NULL;
ui_LBLrewards= NULL;
ui_Image4= NULL;

}
