// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SensESP Round Display

#include "ui.h"

void ArcObenValueChange(lv_event_t * e)
{
	// Your code here
}

void SWonChecked(lv_event_t * e)
{
	// Your code here
}

void SWOnUnchecked(lv_event_t * e)
{
	// Your code here
}
