// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SensESP Round Display

#include "ui.h"

lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_ARCbatLevel = NULL;lv_obj_t *ui_LBLunten = NULL;lv_obj_t *ui_ARCoben = NULL;lv_obj_t *ui_LBLoben = NULL;lv_obj_t *ui_SWon = NULL;lv_obj_t *ui_SWregen = NULL;
// event funtions
void ui_event_ARCoben( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_label_set_property(ui_LBLoben, _UI_LABEL_PROPERTY_TEXT, "");
}
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      ArcObenValueChange( e );
}
}

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ARCbatLevel = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_ARCbatLevel, 235);
lv_obj_set_height( ui_ARCbatLevel, 235);
lv_obj_set_align( ui_ARCbatLevel, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_ARCbatLevel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_arc_set_range(ui_ARCbatLevel, 0,4095);
lv_arc_set_value(ui_ARCbatLevel, 1000);
lv_arc_set_bg_angles(ui_ARCbatLevel,5,175);

lv_obj_set_style_bg_color(ui_ARCbatLevel, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ARCbatLevel, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_LBLunten = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_LBLunten, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LBLunten, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LBLunten, 2 );
lv_obj_set_y( ui_LBLunten, 81 );
lv_obj_set_align( ui_LBLunten, LV_ALIGN_CENTER );
lv_label_set_text(ui_LBLunten,"Text");

ui_ARCoben = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_ARCoben, 235);
lv_obj_set_height( ui_ARCoben, 235);
lv_obj_set_align( ui_ARCoben, LV_ALIGN_CENTER );
lv_obj_set_scrollbar_mode(ui_ARCoben, LV_SCROLLBAR_MODE_ON);
lv_arc_set_range(ui_ARCoben, 0,4095);
lv_arc_set_value(ui_ARCoben, 2047);
lv_arc_set_bg_angles(ui_ARCoben,185,355);
lv_arc_set_mode(ui_ARCoben, LV_ARC_MODE_SYMMETRICAL);

ui_LBLoben = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_LBLoben, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LBLoben, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LBLoben, -1 );
lv_obj_set_y( ui_LBLoben, -76 );
lv_obj_set_align( ui_LBLoben, LV_ALIGN_CENTER );
lv_label_set_text(ui_LBLoben,"Text");

ui_SWon = lv_switch_create(ui_Screen1);
lv_obj_set_width( ui_SWon, 100);
lv_obj_set_height( ui_SWon, 25);
lv_obj_set_x( ui_SWon, 0 );
lv_obj_set_y( ui_SWon, 48 );
lv_obj_set_align( ui_SWon, LV_ALIGN_CENTER );
lv_obj_set_ext_click_area(ui_SWon, 2);

lv_obj_set_style_bg_color(ui_SWon, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SWon, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_SWregen = lv_switch_create(ui_Screen1);
lv_obj_set_width( ui_SWregen, 100);
lv_obj_set_height( ui_SWregen, 25);
lv_obj_set_x( ui_SWregen, 0 );
lv_obj_set_y( ui_SWregen, 12 );
lv_obj_set_align( ui_SWregen, LV_ALIGN_CENTER );
lv_obj_set_ext_click_area(ui_SWregen, 2);

lv_obj_set_style_bg_color(ui_SWregen, lv_color_hex(0x7488DE), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SWregen, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_SWregen, lv_color_hex(0x2B00FF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SWregen, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_ARCoben, ui_event_ARCoben, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_ARCbatLevel= NULL;
ui_LBLunten= NULL;
ui_ARCoben= NULL;
ui_LBLoben= NULL;
ui_SWon= NULL;
ui_SWregen= NULL;

}
